### ISSUE TITLE
Wrong Packages

### ISSUE THREAD

**Issue by devupau** [creativetimofficial/ct-material-blog-pro-laravel#1]
# Expected Behavior

Material Kit PRO - v2.2.0
Material Dashboard PRO - v2.1.2

# Current Behavior

Material Kit PRO - v2.1.1
Material Dashboard PRO - v2.1.0

**Comment by teamupdivision** [comment]
Hello, I'm sorry for the late reply.
Thank you for using Creative Tim products.
What is the problem with the versions?

**Comment by devupau** [comment]
Cool story, bruh.
