### ISSUE TITLE
Cannot delete or update a parent row: a foreign key constraint fails when deleting an article

### ISSUE THREAD

**Issue by cregx** [creativetimofficial/ct-material-blog-pro-laravel#2]
# Current used version: **1.0.1**

# Expected Behavior

After clicking **on delete an article**, it should be possible to delete it without exceptions.

# Current Behavior

When I try to delete a blog article under **articles in the dashboard**, an exception occurs.
# Failure Information (for bugs)

SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`db123456x0987654`.`comments`, CONSTRAINT `comments_article_id_foreign` FOREIGN KEY (`article_id`) REFERENCES `articles` (`id`)) (SQL: delete from `articles` where `id` = 2)

## (Maybe a) possible solution:

In the migration file `2019_09_09_085054_create_comments_table.php` **change** the following code =>

`$table->foreign('article_id')->references('id')->on('articles');`

 **to**: 

`$table->foreign('article_id')->references('id')->on('articles')->onDelete('cascade') `

**Comment by teamupdivision** [comment]
Hi there,

Sorry for the late response to your inquiry. 
We could not reproduce the bug, but we ran some tests, and now everything seems to work fine.

Thank you!
