### ISSUE TITLE
Another route has already been assigned name [blog.search]

### ISSUE THREAD

**Issue by ghost** [creativetimofficial/ct-material-blog-pro-laravel#4]
in the file routes/web.php  there are 2 routes named the same, it causes trouble wen you try to run php artisan optimize.

    Route::namespace('Blog')->group(function () {
    Route::get('article/{article}', 'ArticleController@show')->name('blog.article.show');
    Route::post('comments/{article}', 'CommentsController@store')->name('blog.comments.store');

    Route::get('search/{search}', 'SearchController@index')->name('blog.search'); <----------------

    Route::get('category/{category}', 'CategoryController@index')->name('blog.category');
    Route::get('tag/{tag}', 'TagController@index')->name('blog.tag');
    Route::get('author/{user}', 'AuthorController@index')->name('blog.author');
    Route::get('all_articles', 'ArticleController@index')->name('blog.article.index');

    Route::get('search', 'SearchController@index')->name('blog.search');  <----------------

    Route::post('article/{article}', 'ArticleController@store')->name('blog.article.store');
    Route::post('newsletter', 'NewsletterController@store')->name('blog.newsletter.store');
})`

**Comment by teamupdivision** [comment]
Hi R. Cloeck,

We apologies for the late response.
We fixed the problem you described, try again as it should work smoothly right now.

Thank you!
