### ISSUE TITLE
Can't find app.scss and app.js 

### ISSUE THREAD

**Issue by sergioalejanpro** [creativetimofficial/ct-material-blog-pro-laravel#5]
Hello... 

npm run prod can't find 

resources/js/app.js
resources/sass/app.scss

ERROR in multi ./resources/js/app.js ./resources/sass/app.scss
Module not found: Error: Can't resolve 'C:\laravel\blog\resources\js\app.js' in 'C:\laravel\blog'
 @ multi ./resources/js/app.js ./resources/sass/app.scss /js/app[0]

ERROR in multi ./resources/js/app.js ./resources/sass/app.scss
Module not found: Error: Can't resolve 'C:\laravel\blog\resources\sass\app.scss' in 'C:\laravel\blog'
 @ multi ./resources/js/app.js ./resources/sass/app.scss /js/app[1]

So there is no chance to minify/optimize the code...

**Comment by teamupdivision** [comment]
Hi @sergioalejanpro,

Sorry for the late reply and thanks for reporting this issue.

We're currently working on checking this. Thanks for your patience! 

All the best

**Comment by teamupdivision** [comment]
Hi @sergioalejanpro,

Thanks again for reporting this issue and for using Creative Tim products.

We've pushed a fix to this problem.
You can access it by downloading the product from the downloads section in the Creative Tim website.

All the best

**Comment by teamupdivision** [comment]
Hi @sergioalejanpro,

Hope this solved the problem. I will go ahead and close this ticket.

Best,
UPDIVISION Team

P.S. If you need help with any of your projects, we're happy to get in touch. We do custom development for start-ups and companies across the globe (you can check out our portfolio here https://updivision.com/portfolio and some happy clients over here https://updivision.com/testimonials). Don`t hesitate to drop us a line at office@updivision.com or by using our contact form (https://updivision.com/contact).
