### ISSUE TITLE
Failure To Update Article Content

### ISSUE THREAD

**Issue by ajmt93** [creativetimofficial/ct-material-blog-pro-laravel#6]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ Y ] I am running the latest version
- [ Y ] I checked the documentation and found no answer
- [ Y ] I checked to make sure that this issue has not already been filed
- [ Y ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Editing and saving the content of an article will have the new content saved.

# Current Behavior

The content value does not get updated.

# Failure Information (for bugs)

I have run a dd() on the $request value in ArticleController::update(), and the $request appears to not have the updated content at that point.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. log into an author account.
2. create an article with content.
3. go to edit article.
4. save.
5. content does not update.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device: Occurs on Desktop, Laptop, and a DigitalOcean droplet
* Operating System: Windows 10 -> VirtualBox -> Ubuntu 18.04 (64-bit)
* Browser and Version: Google Chrome Version 105.0.5195.127

## Failure Logs

There are no Failure Logs, as update runs "successfully"

**Comment by teamupdivision** [comment]
Hello,

Thank you for using creative TIM products. 

We are looking into the issue and will get back to you as soon as possible.

Thank you.

**Comment by ajmt93** [comment]
I see this has been closed, but my issue persists. Were you not able to recreate the issue?

**Comment by teamupdivision** [comment]
Hello, 

We apologies for the inconvenience. The issue was closed due to inactivity. 

We will get back as soon as possible with any requests or answers.

Thank you.

**Comment by teamupdivision** [comment]
Hello,

The content seems to be missing when updating the article, so please in your app/Http/Controllers/ArticleController.php file replace the update function with this:
    public function update(ArticleRequest $request, Article $article)
    { 
        $article->update(
            $request->merge([
                'picture' => $request->photo ? $request->photo->store('articles', 'public') : null,
                'status' => $request->status ? 'published' : 'draft',
                'show_on_homepage' => $request->show_on_homepage ? 1 : 0,
                'publish_date' => $request->publish_date ? Carbon::parse($request->publish_date)->format('Y-m-d') : null,
                'content' => $request->content
            ])->except([$request->hasFile('photo') ? '' : 'picture'])
        );

        $article->tags()->sync($request->get('tags'));

        return redirect()->route('article.index')->withStatus(__('Article successfully updated.'));
    }



Please let me know if it works. Thank you.

**Comment by teamupdivision** [comment]
Hello, 

Can we go ahead and consider this ticket closed? 

Has the issue been resolved?

Thank you.
