### ISSUE TITLE
[Bug] php version for material blog pro for laravel

### ISSUE THREAD

**Issue by rdfsondo** [creativetimofficial/ct-material-blog-pro-laravel#7]
### Version
Material Blog PRO Laravel Version - 1.0.3
### Reproduction link
https://material-blog-pro-laravel.creative-tim.com/?ref=mbl-readme
### Operating System
Windows 10 Pro
### Device
Laptop
### Browser & Version
google Chrome - Version 108.0.5359.125
### Steps to reproduce
Hello,
i just bougth material blog pro (company) for laravel, but i am facing difficulties to install it. I am running php 8.1.5 on my machine with most of my applications. When tryning to run composer install, i received the following error message : Root composer.json requires php ^7.3.0 but your php version (8.1.5) does not satisfy that requirement
Is it not possible to run material blog pro laravel with php 8?
### What is expected?
I expected the application to work smoothly
### What is actually happening?
Error message : Root composer.json requires php ^7.3.0 but your php version (8.1.5) does not satisfy that requirement

---

**Comment by teamupdivision** [comment]
Hello, 

Thank you for using Creative TIM products!

We tested on our side, and we could not recreate the issue. 

Could you please share a screen shot with composer.json?

Thank you.

**Comment by rdfsondo** [comment]
![composer install](https://user-images.githubusercontent.com/122024879/210999259-3b11842f-1dc5-4442-aa6c-8872b4e732a6.jpg)
Hello,Please find attached a screen shot of the error message.
Kind regards
Desire SONDO. 

    Le vendredi 6 janvier 2023 à 07:04:57 UTC, Updivision Team ***@***.***> a écrit :  
 
 


Hello,

Thank you for using Creative TIM products!

We tested on our side, and we could not recreate the issue.

Could you please share a screen shot with composer.json?

Thank you.

**Comment by teamupdivision** [comment]
Hello, 

Could you please send a screenshot of composer.json? 

Thank you.

**Comment by rdfsondo** [comment]
![composer](https://user-images.githubusercontent.com/122024879/211005007-52e77947-2bc9-478c-af2f-088fd0734ad8.jpg)
Hello, Please find attached a screenshot of composer.json
Kind regards
Desire SONDO. 

    Le vendredi 6 janvier 2023 à 11:16:53 UTC, Updivision Team ***@***.***> a écrit :  
 
 


Hello,

Could you please send a screenshot of composer.json?

Thank you.

**Comment by teamupdivision** [comment]
Hello, 

Could you download the project again and install it and let us know if that fixes the issue?

Thank you.

**Comment by rdfsondo** [comment]
Hello, 
I download the project again and it's now working. Thanks for the support.

**Comment by teamupdivision** [comment]
Hello,

Happy to hear the problem has been solved. We will go ahead and close this ticket. If there is anything else we can help with, please let us know.

Best,
UPDIVISION Team

P.S. If you need help with any of your projects, we're happy to get in touch. We do custom development for start-ups and companies across the globe (you can check out our portfolio here https://updivision.com/portfolio and some happy clients over here https://updivision.com/testimonials). Don`t hesitate to drop us a line at office@updivision.com or by using our contact form (https://updivision.com/contact).
